### ISSUE TITLE
Unclear Spec

### ISSUE THREAD

**Issue by yberdysh** [learn-co-students/rails-restful-index-action-lab-dumbo-web-062518#9]
@maxcell 

This spec makes no sense. The code is correct and the browser is rendering index page correctly, but this spec is not passing even when using the code on the solution branch.

![image](https://user-images.githubusercontent.com/31297135/43102237-867657f4-8e98-11e8-9845-0a92abd873cc.png)

![image](https://user-images.githubusercontent.com/31297135/43102246-8cbc2756-8e98-11e8-9474-b213f1d692d9.png)

**Comment by maxcell** [comment]
Gonna close this since we managed to fix the canonical version!
